# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f65ed69b626b76cf48531444d59b87c54a155f3a63690bd6301ebbf1850c63d74a34138d9751784286364b3875d48d8f9c9013bc642d79f295ab813ae45f4c0f

test:
  secret_key_base: a40070d9ac0a39ed48cd60c22d0db9a44b6411d01ac63fd81b052dbd5c45e60905cd19183ecef620afc6595664089f79afdf2226f8036c2202ca8468f1b773f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
